---
version: "3.7"

services:
  n8n_docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
    command:
      - mkdocs
      - serve
      - "--dev-addr=0.0.0.0:8005"
    volumes:
      - .:/app/n8n-docs
    environment:
      PYTHONPATH: .
      N8N_DOCS_SERVICE: DEV_SERVE
    ports:
      - 8005:8005/tcp
# vim: tabstop=2 softtabstop=2 shiftwidth=2 expandtab
